development:
  adapter: mysql
  database: skate_development
  username: skate
  password: password
  host: 127.0.0.1
  
test:
  adapter: mysql
  database: skate_test
  username: skate
  password: password
  host: 127.0.0.1

