development:
  adapter: postgres
  database: skate_development
  username: akasper
  password: password
  host: localhost
  
test:
  adapter: postgres
  database: skate_test
  username: akasper
  password: password
  host: localhost

